/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package KalkulatorBangunDatar;
import javax.swing.JOptionPane;
import java.awt.event.KeyEvent;
import java.text.DecimalFormat;
/**
 *
 * @author hsamp
 */
public class Trapesium extends javax.swing.JFrame {

    /**
     * Creates new form coba
     */
    public Trapesium() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtSisiAtas = new javax.swing.JTextField();
        txtHasil = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnKembali = new javax.swing.JButton();
        btnHitung = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnHapus = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtSisiBawah = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        txtTinggi = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(659, 450));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(0, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 10));

        txtSisiAtas.setBackground(new java.awt.Color(0, 51, 102));
        txtSisiAtas.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSisiAtas.setForeground(new java.awt.Color(255, 255, 255));
        txtSisiAtas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        txtSisiAtas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSisiAtasActionPerformed(evt);
            }
        });
        txtSisiAtas.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSisiAtasKeyTyped(evt);
            }
        });

        txtHasil.setEditable(false);
        txtHasil.setBackground(new java.awt.Color(0, 51, 102));
        txtHasil.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtHasil.setForeground(new java.awt.Color(255, 255, 255));
        txtHasil.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtHasil.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Sisi Atas Trapesium(CM)");

        btnKembali.setBackground(new java.awt.Color(0, 51, 102));
        btnKembali.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnKembali.setForeground(new java.awt.Color(255, 255, 255));
        btnKembali.setText("KEMBALI");
        btnKembali.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btnKembali.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKembaliActionPerformed(evt);
            }
        });

        btnHitung.setBackground(new java.awt.Color(0, 51, 102));
        btnHitung.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnHitung.setForeground(new java.awt.Color(255, 255, 255));
        btnHitung.setText("HITUNG");
        btnHitung.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btnHitung.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHitung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHitungActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("LUAS TRAPESIUM");

        btnHapus.setBackground(new java.awt.Color(0, 51, 102));
        btnHapus.setFont(new java.awt.Font("Segoe UI", 1, 10)); // NOI18N
        btnHapus.setForeground(new java.awt.Color(255, 255, 255));
        btnHapus.setText("HAPUS");
        btnHapus.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0)));
        btnHapus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("HASIL");

        jLabel5.setFont(new java.awt.Font("SimSun-ExtG", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Rumus Luas Trapesium : (Sisi Atas + Sisi Bawah) / 2 x Tinggi");

        txtSisiBawah.setBackground(new java.awt.Color(0, 51, 102));
        txtSisiBawah.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtSisiBawah.setForeground(new java.awt.Color(255, 255, 255));
        txtSisiBawah.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        txtSisiBawah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSisiBawahActionPerformed(evt);
            }
        });
        txtSisiBawah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtSisiBawahKeyTyped(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Sisi Bawah Trapesium(CM)");

        txtTinggi.setBackground(new java.awt.Color(0, 51, 102));
        txtTinggi.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        txtTinggi.setForeground(new java.awt.Color(255, 255, 255));
        txtTinggi.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51)));
        txtTinggi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTinggiActionPerformed(evt);
            }
        });
        txtTinggi.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtTinggiKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Tinggi Trapesium(CM)");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addComponent(jLabel3))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(btnKembali, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(151, 151, 151))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addGap(15, 15, 15)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel6)
                                            .addComponent(jLabel2)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtSisiBawah, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addComponent(jLabel4)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(txtSisiAtas, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(btnHitung, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addComponent(jLabel3)
                .addGap(6, 6, 6)
                .addComponent(jLabel5)
                .addGap(37, 37, 37)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSisiAtas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(10, 10, 10)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSisiBawah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTinggi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnHitung)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtHasil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(btnKembali))
                .addContainerGap())
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(110, 60, 430, 280);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/KalkulatorBangunDatar/background (1).jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-20, 0, 700, 430);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtSisiAtasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSisiAtasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSisiAtasActionPerformed

    private void btnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKembaliActionPerformed
        // TODO add your handling code here:
        Dashboard kembali1 = new Dashboard();
        kembali1.setVisible(true);
        
        this.dispose();
    }//GEN-LAST:event_btnKembaliActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        // TODO add your handling code here:
        txtSisiAtas.setText("");
        txtSisiBawah.setText("");
        txtTinggi.setText("");
        txtHasil.setText("");
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnHitungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHitungActionPerformed
        // TODO add your handling code here:
        if (txtSisiAtas.getText().isEmpty() && txtSisiBawah.getText().isEmpty() && txtTinggi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(txtTinggi, "Masukkan Sisi Atas, Sisi Bawah Dan Tinggi Terlebih Dahulu", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        } else if (txtSisiAtas.getText().isEmpty() && txtSisiBawah.getText().isEmpty()) {
            JOptionPane.showMessageDialog(txtSisiBawah, "Masukkan Sisi Atas Dan Sisi Bawah Terlebih Dahulu", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        } else if (txtSisiAtas.getText().isEmpty() && txtTinggi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(txtTinggi, "Masukkan Sisi Atas Dan Tinggi Terlebih Dahulu", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        } else if (txtSisiBawah.getText().isEmpty() && txtTinggi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(txtTinggi, "Masukkan Sisi Bawah Dan Tinggi Terlebih Dahulu", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        } else if (txtSisiAtas.getText().isEmpty()) {
            JOptionPane.showMessageDialog(txtSisiAtas, "Masukkan Masukkan Sisi Atas Terlebih Dahulu", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        } else if (txtSisiBawah.getText().isEmpty()) {
            JOptionPane.showMessageDialog(txtSisiBawah, "Masukkan Sisi Bawah Terlebih Dahulu", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        } else if (txtTinggi.getText().isEmpty()) {
            JOptionPane.showMessageDialog(txtTinggi, "Masukkan Tinggi Terlebih Dahulu", "Invalid Input", JOptionPane.WARNING_MESSAGE);
        } else {
            float sisi = Float.parseFloat(txtSisiAtas.getText())+Float.parseFloat(txtSisiBawah.getText());
            float bagi = sisi / 2;
            float luas = bagi*Float.parseFloat(txtTinggi.getText());
            DecimalFormat df = new DecimalFormat("#.###");
            txtHasil.setText(df.format(luas)+"CM");
        }
    }//GEN-LAST:event_btnHitungActionPerformed

    private void txtSisiAtasKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSisiAtasKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
                String text = txtSisiAtas.getText();
                // Jika input bukan angka, bukan titik, dan bukan backspace
                if (!Character.isDigit(c) && c != '.' && c != KeyEvent.VK_BACK_SPACE) {
                    evt.consume(); // Batalkan input
                    JOptionPane.showMessageDialog(txtSisiAtas, "Tidak Boleh Mengisi Huruf!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                }
                if (c == '.' && text.contains(".")) {
                    evt.consume();
                    JOptionPane.showMessageDialog(txtSisiAtas, "Hanya bisa menggunakan satu titik desimal!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                }
                if (c == '.' && text.isEmpty()) {
                    evt.consume();
                    JOptionPane.showMessageDialog(txtSisiAtas, "Titik desimal tidak boleh di awal!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                }
    }//GEN-LAST:event_txtSisiAtasKeyTyped

    private void txtSisiBawahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSisiBawahActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSisiBawahActionPerformed

    private void txtSisiBawahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSisiBawahKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
                String text = txtSisiBawah.getText();
                // Jika input bukan angka, bukan titik, dan bukan backspace
                if (!Character.isDigit(c) && c != '.' && c != KeyEvent.VK_BACK_SPACE) {
                    evt.consume(); // Batalkan input
                    JOptionPane.showMessageDialog(txtSisiBawah, "Tidak Boleh Mengisi Huruf!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                }
                if (c == '.' && text.contains(".")) {
                    evt.consume();
                    JOptionPane.showMessageDialog(txtSisiBawah, "Hanya bisa menggunakan satu titik desimal!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                }
                if (c == '.' && text.isEmpty()) {
                    evt.consume();
                    JOptionPane.showMessageDialog(txtSisiBawah, "Titik desimal tidak boleh di awal!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                }
    }//GEN-LAST:event_txtSisiBawahKeyTyped

    private void txtTinggiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTinggiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTinggiActionPerformed

    private void txtTinggiKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTinggiKeyTyped
        // TODO add your handling code here:
        char c = evt.getKeyChar();
                String text = txtSisiBawah.getText();
                // Jika input bukan angka, bukan titik, dan bukan backspace
                if (!Character.isDigit(c) && c != '.' && c != KeyEvent.VK_BACK_SPACE) {
                    evt.consume(); // Batalkan input
                    JOptionPane.showMessageDialog(txtSisiBawah, "Tidak Boleh Mengisi Huruf!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                }
                if (c == '.' && text.contains(".")) {
                    evt.consume();
                    JOptionPane.showMessageDialog(txtSisiBawah, "Hanya bisa menggunakan satu titik desimal!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                }
                if (c == '.' && text.isEmpty()) {
                    evt.consume();
                    JOptionPane.showMessageDialog(txtSisiBawah, "Titik desimal tidak boleh di awal!", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                }
    }//GEN-LAST:event_txtTinggiKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Trapesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Trapesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Trapesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Trapesium.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Trapesium().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnHitung;
    private javax.swing.JButton btnKembali;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtHasil;
    private javax.swing.JTextField txtSisiAtas;
    private javax.swing.JTextField txtSisiBawah;
    private javax.swing.JTextField txtTinggi;
    // End of variables declaration//GEN-END:variables
}
